
const tabbar = [
	{
		path: '/message',
		title: '消息',
		key: 'message',
		dot: true,
		icon: '',
		selected_icon: '',
		local_icon: require('../assets/tabbar/message.png'),
		local_selected_icon: require('../assets/tabbar/message_select.png'),
		unselectColor: '#949494',
		selectColor: '#33A3F4',
	},
	{
		path: '/word',
		title: '文档',
		key: 'word',
		dot: false,
		icon: '',
		selected_icon: '',
		local_icon: require('../assets/tabbar/word.png'),
		local_selected_icon: require('../assets/tabbar/word_select.png'),
		unselectColor: '#949494',
		selectColor: '#33A3F4',
	},
	{
		path: '/new',
		title: '新校招',
		key: 'new',
		dot: false,
		icon: '',
		selected_icon: '',
		local_icon: require('../assets/tabbar/new.png'),
		local_selected_icon: require('../assets/tabbar/new_select.png'),
		unselectColor: '#949494',
		selectColor: '#33A3F4',
	},
	{
		path: '/contact',
		title: '通讯录',
		key: 'contact',
		dot: false,
		icon: '',
		selected_icon: '',
		local_icon: require('../assets/tabbar/contact.png'),
		local_selected_icon: require('../assets/tabbar/contact_select.png'),
		unselectColor: '#949494',
		selectColor: '#33A3F4',
	},
	{
		path: '/discover',
		title: '发现',
		key: 'discover',
		dot: false,
		icon: '',
		selected_icon: '',
		local_icon: require('../assets/tabbar/discover.png'),
		local_selected_icon: require('../assets/tabbar/discover_select.png'),
		unselectColor: '#949494',
		selectColor: '#33A3F4',
	},
]

export default tabbar